# Generated by Django 4.1.7 on 2025-03-25 05:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GardenHiveApp', '0003_booking_cancel_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='added_at',
            new_name='date_joined',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='position',
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Sales', 'Sales'), ('Support', 'Support')], default='Staff', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cancel_deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 4, 5, 23, 9, 216634, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='nursery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GardenHiveApp.nursery'),
        ),
    ]
