# Generated by Django 4.1.7 on 2025-03-24 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GardenHiveApp', '0002_cart_quantity_alter_cart_added_at_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel_deadline',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 3, 15, 53, 33, 453259, tzinfo=datetime.timezone.utc)),
        ),
    ]
